version: "3.6"

volumes:
  wg-vol: {}

networks:
  wgnetwork:
    name: wgnetwork

services:
  api:
    container_name: wg_flask
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DEBUG: 1
      FLASK_DEBUG: 0
      FLASK_APP: app
      FLASK_RUN_PORT: 80
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@pg:5432/db_wg
    ports:
      - "5010:80"
    depends_on:
      - pg
    links:
      - pg
    volumes:
      - ./app:/usr/src/app
    networks:
      - wgnetwork

  pg:
    container_name: wg_pg
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_wg
    ports:
      - "5434:5432"
    volumes:
      - wg-vol:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wgnetwork
